Param( 
    [Parameter(Mandatory = $true, Position = 1, HelpMessage = "path to dotCover.exe")] [String] $dotCoverExePath,
    [Parameter(Mandatory = $false, Position = 2, HelpMessage = "path to powershell.exe")] [String] $powerShellExePath = "c:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
)

[string]$currentPath = Split-Path $MyInvocation.MyCommand.Path
[string]$solutionDir = Join-Path $currentPath '..' | Resolve-Path
[string]$runTestsScriptPath = "$currentPath\UnitTests.ps1"
[string]$outputFilePath = "$solutionDir\TestCoverageResults.dcvr"

# execute tests in dotCover session and record coverage of executed tests to output file
& $dotCoverExePath cover `
    /TargetExecutable=$powerShellExePath `
    /TargetArguments=$runTestsScriptPath `
    /Filters="+:module=ThoughtWorks.CTM;-:module=*Test*;" `
    /Output=$outputFilePath

Write-Host -foregroundcolor Green "dotCover report is saved to [$outputFilePath]"

# pass code coverage report generated by dotCover to TeamCity using service messages
Write-Host "##teamcity[importData type='dotNetCoverage' tool='dotcover' path='$outputFilePath' verbose='true']"